### ISSUE TITLE
Unable to build samples under Linux

### ISSUE THREAD

**Issue by barotto** [mikke89/libRocket#4]
Whilst trying to compile the samples under Linux, this is the error I got:
```
In file included from /usr/include/X11/Xlib.h:44:0,
                 from /usr/include/GL/glx.h:30,
                 from Samples/shell/include/ShellOpenGL.h:44,
                 from Samples/shell/include/ShellRenderInterfaceOpenGL.h:32,
                 from Samples/shell/src/ShellRenderInterfaceOpenGL.cpp:29:
Include/Rocket/Core/Tween.h:39:14: error: expected identifier before numeric constant
  enum Type { None, Back, Bounce, Circular, Cubic, Elastic, Exponential, Linear, Quadratic, Quartic, Quintic, Sine, Callback, Count };
              ^
```
Apparently `None` is already defined as a preprocessor macro in the system header file X.h:
```
/usr/include/X11/X.h:115:0:
 #define None                 0L /* universal null resource or null atom */
```
Any idea on the best way to fix this?
I hate defines...

**Comment by mikke89** [comment]
Ugh, that is one #define that is made to cause problems. A quick web search tells us we're not alone. I think the best procedure is to #undef it, as it seems we're not using it in any places. Does that work for you, i.e at the end of the #includes in ShellOpenGL.h?
